[package]
name = "magicapi-gateway"
version = "0.1.0"
edition = "2021"
description = "A high-performance AI Gateway proxy for routing requests to various AI providers"
authors = ["MagicAPI Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/magicapi/ai-gateway"
documentation = "https://github.com/magicapi/ai-gateway"
readme = "README.md"
keywords = ["ai", "gateway", "proxy", "openai", "anthropic"]
categories = ["web-programming", "api-bindings", "asynchronous"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7", features = ["http2"] }
tokio = { version = "1.0", features = ["full"] }
tower-http = { version = "0.5", features = ["cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.11", features = ["stream", "json"] }
futures = "0.3"
http = "1.0"
tower = "0.4"
bytes = "1.0"
dotenv = "0.15"
futures-util = "0.3"
once_cell = "1.18"